# Generated by Django 3.1.8 on 2021-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
