# Generated by Django 3.1.8 on 2021-06-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bids_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
