# Generated by Django 3.1.8 on 2021-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
