# Generated by Django 3.1.8 on 2021-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210609_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isopen',
            field=models.BooleanField(default=True),
        ),
    ]
